
<MainWindow>:
    orientation: "horizontal"
            
    BoxLayout:
        orientation: "vertical"
        Label: 
            text: "label 3"
        Button:
            text: "text3"
            
<Box1>:
    orientation: "vertical"
    
    Button:
        text: "text1"
    Button:
        text: "text1.2"
        
            
<Box2>:
    orientation: "vertical"
    
    Button: 
        text: "text2"